export enum CustomMessage {
    invalidForm = 'Invalid Form!',
    invalidCredential = 'Invalid credentials',
    loginSuccess = 'Logged in sucessfully',
    leaveApplySuccess = 'Leave applied succesfully',
    error = 'Server error. Please try again.',
    commentRequired = 'Please enter comment',
    leaveAccepted = 'Leave accepted succesfully',
    leaveRejected = 'Leave rejected succesfully',
    resignationAccepted = 'Resignation accepted succesfully',
    resignationRejected = 'Resignation rejected succesfully',
    dateWarningWithTime = 'More than one day\'s leave can not be generated with time.',
    timeWarningWithDate = 'You can not select time when you are applying for leave more than one day.',
    maxShiftTimeWarning = 'You can not apply leave for more than 4 hour.',
    passwordChangedSuccess = 'Password updated succesfully',
    invalidCurrentPassword = 'Current password is incorrect.',
    registerSuccess = 'Your request is submitted succesfully.Please wait while we verify your details.Thanks',
    alreadyRegistered = 'Your request is already submitted.Please wait while we verify your details and get back to you.Thanks',
    userCreatedSuccess = 'User created successfully',
    alreadyExist = 'User already exist'
}
